WIP

diff --git a/flatcar/nvidia-driver b/flatcar/nvidia-driver
--- a/flatcar/nvidia-driver
+++ b/flatcar/nvidia-driver
@@ -6,159 +6,132 @@ set -eu
 RUN_DIR=/run/nvidia
 PID_FILE=${RUN_DIR}/${0##*/}.pid
 DRIVER_VERSION=${DRIVER_VERSION:?"Missing driver version"}
-NVIDIA_BINUITLS_DIR=/opt/nvidia/binutils
-NVIDIA_KMODS_DIR=/opt/nvidia/${DRIVER_VERSION}
+#NVIDIA_BINUITLS_DIR=/opt/nvidia/binutils
+#NVIDIA_KMODS_DIR=/opt/nvidia/${DRIVER_VERSION}
+GPU_DIRECT_RDMA_ENABLED=${GPU_DIRECT_RDMA_ENABLED:-false}
 
-export COREOS_RELEASE_CHANNEL=stable
-COREOS_RELEASE_BOARD=amd64-usr
-COREOS_ALL_RELEASES="https://www.flatcar-linux.org/releases-json/releases-${COREOS_RELEASE_CHANNEL}.json"
+KERNEL_TYPE=kernel
+
+#export COREOS_RELEASE_CHANNEL=stable
+#COREOS_RELEASE_BOARD=amd64-usr
+#COREOS_ALL_RELEASES="https://www.flatcar-linux.org/releases-json/releases-${COREOS_RELEASE_CHANNEL}.json"
 
 export DEBIAN_FRONTEND=noninteractive
 
-# The developement environment is required to access gcc and binutils
-# binutils is particularly required even if we have precompiled kernel interfaces 
-# as the ld version needs to match the version used to build the linked kernel interfaces later
-# Note that container images can only contain precompiled (but not linked) kernel modules
-_install_development_env() {
+_relocate_flatcar() {
+    set -euo pipefail
 
-    echo "Installing the Flatcar development environment on the filesystem $PWD..."
+    #shopt -s nullglob
 
-    # Get the flatcar development environment for a given kernel version. 
-    # The environment is mounted on a loop device and then we chroot into 
-    # the mount to build the NVIDIA kernel driver interface. 
-    # The resulting module files and module dependencies are then archived.
-    local latest_release
-    latest_release=$(echo "${COREOS_RELEASE_VERSION}" | awk '{ print $1 }')
-    local dev_image="flatcar_developer_container.bin"
-    local dev_image_url="https://${COREOS_RELEASE_CHANNEL}.release.flatcar-linux.net/${COREOS_RELEASE_BOARD}/${latest_release}/${dev_image}.bz2"
-
-    curl -Ls "${dev_image_url}" | bzip2 -dq > "${dev_image}"
-    local sector_size
-    sector_size=$(fdisk -l "${dev_image}" | grep "^Sector size" | awk '{ print $4 }')
-    local sector_start
-    sector_start=$(fdisk -l "${dev_image}" | grep "^${dev_image}*" | awk '{ print $2 }')
-    local offset_limit=$((sector_start * sector_size))
-
-    mkdir -p /mnt/coreos
-    local loop_dev="/dev/loop0"
-    _exec mount -o loop=${loop_dev},offset=${offset_limit} ${dev_image} /mnt/coreos
-
-    # add more space to the device
-    local mount_path
-    mount_path=$(losetup --list --noheadings -O BACK-FILE "${loop_dev}")
-    dd if=/dev/zero bs=1MiB of="${mount_path}" conv=notrunc oflag=append count=3000
-    losetup -c ${loop_dev}
-    resize2fs ${loop_dev}
-
-    # Version.txt contains some pre-defined environment variables 
-    # that we will use when building the kernel modules
-    curl -fOSsL https://${COREOS_RELEASE_CHANNEL}.release.flatcar-linux.net/${COREOS_RELEASE_BOARD}/${latest_release}/version.txt
-    cp version.txt /usr/src
-
-    # Prepare the mount point for the chroot
-    cp --dereference /etc/resolv.conf /mnt/coreos/etc/
-    _exec mount --types proc /proc /mnt/coreos/proc
-    _exec mount --rbind /sys /mnt/coreos/sys
-    _exec mount --make-rslave /mnt/coreos/sys
-    _exec mount --rbind /dev /mnt/coreos/dev
-    _exec mount --make-rslave /mnt/coreos/dev
-    mkdir -p /mnt/coreos/usr/src
-    _exec mount --rbind /usr/src /mnt/coreos/usr/src
-
-    # Archive the binutils since we need the linker for re-linking the modules
-    if [ ! -e ${NVIDIA_BINUITLS_DIR} ]; then
-        mkdir -p ${NVIDIA_BINUITLS_DIR}/libs
-        mkdir -p ${NVIDIA_BINUITLS_DIR}/bin
+    hostlds=( /host-lib/usr/lib64/ld-linux-*.so.* )
+    if [[ ${#hostlds[@]} -eq 0 ]]; then
+        echo "** no dynamic loaders found"
+        return 1
     fi
-    local binutils_ver=$(ls -d /mnt/coreos/usr/lib64/binutils/x86_64-cros-linux-gnu/*)
-    binutils_ver=${binutils_ver##*/}
-    cp -r /mnt/coreos/usr/x86_64-cros-linux-gnu/binutils-bin/${binutils_ver}/* ${NVIDIA_BINUITLS_DIR}/bin/
-    cp -r /mnt/coreos/usr/lib64/binutils/x86_64-cros-linux-gnu/${binutils_ver}/* ${NVIDIA_BINUITLS_DIR}/libs/
+    if [[ ${#hostlds[@]} -gt 1 ]]; then
+        echo "** more than one fitting dynamic loader found, picking first"
+    fi
+    hostld=${hostlds[0]}
+    echo "** Found host dynamic loader: ${hostld}"
 
+    kdirs=( /lib/modules/${KERNEL_VERSION}/build )
+    if [[ ${#kdirs[@]} -eq 0 ]]; then
+        echo "** no kernel module tools directories found"
+        return 1
+    fi
+    if [[ ${#kdirs[@]} -gt 1 ]]; then
+        echo "** more than one fitting kernel module tools directory found, picking first"
+    fi
+    kdir=${kdirs[0]}
+    echo "** Found kernel tools directory: ${kdir}"
+
+    tools=(
+        scripts/basic/fixdep
+        scripts/mod/modpost
+        tools/objtool/objtool
+    )
+
+    for tool in "${tools[@]}"; do
+        host_tool=${kdir}/${tool}
+        if [[ ! -f ${host_tool} ]]; then
+            echo "${tool@Q} not found in ${kdir@Q}, not patching"
+            continue
+        fi
+        echo "** Setting host dynamic loader for ${tool@Q}"
+        patchelf \
+            --set-interpreter "${hostld}" \
+            --set-rpath /host-lib/usr/lib64 \
+            "${host_tool}"
+    done
 }
 
-_cleanup_development_env() {
-    echo "Cleaning up the development environment..."
-    _exec umount -l /mnt/coreos
-    rm -rf /mnt/coreos
-    rm -f "/usr/src/nvidia-${DRIVER_VERSION}/flatcar_developer_container.bin"
-}
-
-# Install the kernel modules header/builtin/order files and generate the kernel version string.
-# The kernel sources are installed on the loop mount by following the official documentation at 
-# https://kinvolk.io/docs/flatcar-container-linux/latest/reference/developer-guides/kernel-modules/
-# We also ensure that the kernel version string (/proc/version) is written so it can be 
-# archived along with the precompiled kernel interfaces. 
-_install_prerequisites() (
+_install_prerequisites() {
     
     rm -rf "/lib/modules/${KERNEL_VERSION}"
     rm -rf /usr/src/linux*
-
+    #rm -rf /host-lib
+    
     # Gather the tag for the release matching the current kernel version.
     local kernel
     kernel=$(echo "${KERNEL_VERSION}" | cut -d "-" -f1)
     export COREOS_RELEASE_VERSION=$(curl -Ls "${COREOS_ALL_RELEASES}" | jq -r --arg kernel_ver "${kernel}" 'to_entries[] | select ((.value.major_software.kernel[0] == $kernel_ver) and (.key != "current")) | .key')
 
-    _install_development_env 
+    local versionid=$(. /host-etc/os-release; echo $VERSION_ID)
+    local channel=
+    local board=
+    case "$versionid" in
+      *.2.*)
+        channel=stable;;
+      *.1.*)
+        channel=beta;;
+      *.0.*)
+        channel=alpha;;
+    esac
+
+    case "$(uname -m)" in
+      x86_64)
+        board=amd64-usr;;
+      aarch64)
+        board=arm64-usr;;
+    esac
     echo "Installing the Flatcar kernel sources into the development environment..."
 
-    cat <<'EOF' | chroot /mnt/coreos /bin/bash
-KERNEL_VERSION=$(cat /usr/src/linux/include/config/kernel.release || ls /lib/modules)
-KERNEL_STRING=$(echo "${KERNEL_VERSION}" | cut -d "-" -f1)
-echo "Installing kernel sources for kernel version ${KERNEL_VERSION}..."
-source /etc/os-release
-[ $(echo ${VERSION_ID//./ } | awk '{print $1}') -lt 2346 ] && \
- echo "Fixing path for flatcar kernel sources..." && \
- sed -i -e "s;http://builds.developer.core-os.net/boards/;https://storage.googleapis.com/flatcar-jenkins/boards/;g" /etc/portage/make.conf
-export $(cat /usr/src/version.txt | xargs)
-emerge-gitclone \
-&& export OVERLAY_VERSION="${COREOS_RELEASE_CHANNEL}-${COREOS_RELEASE_VERSION}" \
-&& export PORTAGE_VERSION="${COREOS_RELEASE_CHANNEL}-${COREOS_RELEASE_VERSION}" \
-&& git -C /var/lib/portage/coreos-overlay checkout "$OVERLAY_VERSION" \
-&& git -C /var/lib/portage/portage-stable checkout "$PORTAGE_VERSION"
-emerge -gKq coreos-sources \
-|| echo "failed to download binaries, fallback build from source:" \
-&& emerge -q --jobs 4 --load-average 4 coreos-sources
-# Ensure that the symbolic link points to the right kernel version
-rm -f /usr/src/linux
-ln -s /usr/src/linux-${KERNEL_STRING}-coreos /usr/src/linux
-cp /lib/modules/${KERNEL_VERSION}/build/.config /usr/src/linux
-make -C /usr/src/linux modules_prepare > /dev/null
-cp /lib/modules/${KERNEL_VERSION}/build/Module.symvers /usr/src/linux/
-depmod ${KERNEL_VERSION}
-mkdir -p /usr/src/linux/proc
-cp /proc/version /usr/src/linux/proc/
+    mkdir -p /host-lib
+    mkdir -p /lib/modules
 
-echo "Compiling NVIDIA driver kernel modules with $(gcc --version | head -1)..."
-cp /lib/modules/${KERNEL_VERSION}/build/scripts/module.lds /usr/src/nvidia-*/kernel
-cd /usr/src/nvidia-*/kernel
-export IGNORE_CC_MISMATCH=1
-export IGNORE_MISSING_MODULE_SYMVERS=1
-make -s -j SYSSRC=/lib/modules/${KERNEL_VERSION}/source nv-linux.o nv-modeset-linux.o > /dev/null
-EOF
-    mkdir -p /lib/modules/${KERNEL_VERSION}
-    cp -r /mnt/coreos/lib/modules/${KERNEL_VERSION}/* /lib/modules/${KERNEL_VERSION}/
-    depmod "${KERNEL_VERSION}"
-    
-    _cleanup_development_env
-)
+    curl --retry 3 -LJO "https://${channel}.release.flatcar-linux.net/${board}/${versionid}/flatcar-container.tar.gz"
+    tar xf flatcar-container.tar.gz -C /lib/modules ./usr/lib/modules --strip-components 4
+    tar xf flatcar-container.tar.gz -C /host-lib ./usr/lib64 --exclude=./usr/lib64/misc/*
+    pushd /lib/modules/${KERNEL_VERSION}/build
+    for i in ../source/include/*; do
+        ln -s ../$i include/
+    done
+    for i in ../source/arch/x86/include/*; do
+        ln -s ../../../$i arch/x86/include/
+    done
+    popd
+
+    _relocate_flatcar
+    mkdir -p /lib/modules/$(uname -r)/proc
+    cp /proc/version /lib/modules/$(uname -r)/proc
+}
 
 # Check if the kernel version requires a new precompiled driver packages.
 _kernel_requires_package() {
     local proc_mount_arg=""
 
     echo "Checking NVIDIA driver packages..."
-    cd "/usr/src/nvidia-${DRIVER_VERSION}/kernel"
+    cd "/usr/src/nvidia-${DRIVER_VERSION}/${KERNEL_TYPE}"
 
     if [ "${KERNEL_VERSION}" != "$(uname -r)" ]; then
-        proc_mount_arg="--proc-mount-point /usr/src/linux/proc"
+        proc_mount_arg="--proc-mount-point /lib/modules/${KERNEL_VERSION}/proc"
     fi
     # Note that mkprecompiled does not handle empty double-quotes;
     # so don't wrap variables in double-quotes
     # The precompiled directory structure is laid out as one directory per KERNEL_VERSION 
     # and it includes the packed kernel interfaces and other files. So we use the following search pattern:
-    for pkg_name in $(ls -d -1 precompiled/*/nvidia-modules* 2> /dev/null); do
-        if ! ../mkprecompiled --match ${pkg_name} ${proc_mount_arg} > /dev/null; then
+    for pkg_name in $(ls -d -1 precompiled/** 2> /dev/null); do
+        if  ! ../mkprecompiled --match ${pkg_name} ${proc_mount_arg} ; then
             echo "Found NVIDIA driver package ${pkg_name##*/}"
             return 1
         fi
@@ -167,30 +140,44 @@ _kernel_requires_package() {
 }
 
 # Compile the kernel modules, optionally sign them, and generate a precompiled package for use later.
-_create_driver_package() (
+_create_driver_package() {
     local pkg_name="nvidia-modules-${KERNEL_VERSION%%-*}${PACKAGE_TAG:+-${PACKAGE_TAG}}"
     local nvidia_sign_args=""
     local nvidia_modeset_sign_args=""
     local nvidia_uvm_sign_args=""
+    local nvidia_peermem_sign_args=""
 
-    cd "/usr/src/nvidia-${DRIVER_VERSION}/kernel"
+    trap "make -s -j SYSSRC=/lib/modules/${KERNEL_VERSION}/build clean > /dev/null" EXIT
+    echo "Compiling NVIDIA driver kernel modules..."
+    cd "/usr/src/nvidia-${DRIVER_VERSION}/${KERNEL_TYPE}"
 
     if [ -n "${PRIVATE_KEY}" ]; then
         echo "Signing NVIDIA driver kernel modules..."
         donkey get "${PRIVATE_KEY}" sh -c "PATH=${PATH}:/usr/src/linux-headers-${KERNEL_VERSION}/scripts && \
           sign-file sha512 \$DONKEY_FILE pubkey.x509 nvidia.ko nvidia.ko.sign &&                          \
           sign-file sha512 \$DONKEY_FILE pubkey.x509 nvidia-modeset.ko nvidia-modeset.ko.sign &&          \
-          sign-file sha512 \$DONKEY_FILE pubkey.x509 nvidia-uvm.ko"
+          sign-file sha512 \$DONKEY_FILE pubkey.x509 nvidia-uvm.ko &&
+          sign-file sha512 \$DONKEY_FILE pubkey.x509 nvidia-peermem.ko"
         nvidia_sign_args="--linked-module nvidia.ko --signed-module nvidia.ko.sign"
         nvidia_modeset_sign_args="--linked-module nvidia-modeset.ko --signed-module nvidia-modeset.ko.sign"
         nvidia_uvm_sign_args="--signed"
+        nvidia_peermem_sign_args="--signed"
     fi
+
+    export IGNORE_CC_MISMATCH=1
+    make -s -j$(nproc) CC=gcc-12 SYSSRC=/lib/modules/${KERNEL_VERSION}/build nv-linux.o nv-modeset-linux.o > /dev/null
+
+    find -name '*.ko'
+    echo "Relinking NVIDIA driver kernel modules..."
+    rm -f nvidia.ko nvidia-modeset.ko
+    ld -d -r -o nvidia.ko ./nv-linux.o ./nvidia/nv-kernel.o_binary
+    ld -d -r -o nvidia-modeset.ko ./nv-modeset-linux.o ./nvidia-modeset/nv-modeset-kernel.o_binary
 
     # Note that mkprecompiled does not handle empty double-quotes;
     # so don't wrap variables in double-quotes
     echo "Building NVIDIA driver package ${pkg_name}..."
     ../mkprecompiled --pack ${pkg_name} --description ${KERNEL_VERSION}                              \
-                                        --proc-mount-point /usr/src/linux/proc                       \
+                                        --proc-mount-point /lib/modules/${KERNEL_VERSION}/proc       \
                                         --driver-version ${DRIVER_VERSION}                           \
                                         --kernel-interface nv-linux.o                                \
                                         --linked-module-name nvidia.ko                               \
@@ -204,22 +191,13 @@ _create_driver_package() (
                                         --target-directory .                                         \
                                         --kernel-module nvidia-uvm.ko                                \
                                         ${nvidia_uvm_sign_args}                                      \
+                                        --target-directory .                                         \
+                                        --kernel-module nvidia-peermem.ko                            \
+                                        ${nvidia_peermem_sign_args}                                  \
                                         --target-directory .
-    # Archive the module files, so we can re-link later
-    # The archive is created one per kernel version, including the package created above
-    # and the corresponding module files. 
-    # Finally, delete any linked kernel modules (.ko) as they cannot be part of the container image
-    local archive_dir=precompiled/${KERNEL_VERSION}
-    mkdir -p "${archive_dir}"
-    mv "${pkg_name}" "${archive_dir}"
-    local kmods="nvidia nvidia-uvm nvidia-modeset nvidia-drm"
-    for m in $kmods; do 
-       cp ${m}.mod.o "${archive_dir}"
-       rm -f ${m}.ko
-    done
-    cp modules.order "${archive_dir}"
-    echo "Packaged precompiled driver into $PWD/${archive_dir}"
-)
+    mkdir -p precompiled
+    mv ${pkg_name} precompiled
+}
 
 # Load the kernel modules and start persistenced.
 _load_driver() {
@@ -281,49 +259,17 @@ _unload_driver() {
     return 0
 }
 
-# Link and install the kernel modules from a precompiled package using the nvidia-installer.
 _install_driver() {
     local install_args=()
 
     echo "Installing NVIDIA driver kernel modules..."
-    local base_dir=/usr/src/nvidia-${DRIVER_VERSION}/kernel
-    cd "${base_dir}"
+    cd /usr/src/nvidia-${DRIVER_VERSION}
+    rm -rf /lib/modules/${KERNEL_VERSION}/video
 
     if [ "${ACCEPT_LICENSE}" = "yes" ]; then
         install_args+=("--accept-license")
     fi
-    # Prepare the final destination of the kernel modules and a staging directory 
-    # We will also setup some variables needed in the chroot 
-    # The precompiled kernel interfaces are first unpacked, and then re-linked using 
-    # the same linker that was used to build the precompiled modules 
-    mkdir -p ${NVIDIA_KMODS_DIR}/lib/modules/${KERNEL_VERSION}
-    local staging_dir=${base_dir}/staging/${KERNEL_VERSION}
-    mkdir -p ${staging_dir}
-
-    local pkg_name="nvidia-modules-${KERNEL_VERSION%%-*}${PACKAGE_TAG:+-${PACKAGE_TAG}}"
-    local archive_dir=${base_dir}/precompiled/${KERNEL_VERSION}
-    # Note that mkprecompiled does not handle empty double-quotes;
-    # so don't wrap variables in double-quotes
-    ../mkprecompiled --unpack ${archive_dir}/${pkg_name} -o ${staging_dir}
-    cp ${archive_dir}/*.mod.o ${staging_dir}
-
-    # Re-link the modules by using the binutils we archived from the development 
-    # environment.
-    local old_ld_path=$LD_LIBRARY_PATH
-    export LD_LIBRARY_PATH=${NVIDIA_BINUITLS_DIR}/libs:$LD_LIBRARY_PATH
-    cd ${staging_dir}
-    cp ../../nvidia/nv-kernel.o_binary .
-    cp ../../nvidia-modeset/nv-modeset-kernel.o_binary .
-    echo "Re-linking NVIDIA driver kernel modules..."
-    ${NVIDIA_BINUITLS_DIR}/bin/ld -d -r -T ${base_dir}/module.lds -o nvidia.ko ./nv-linux.o ./nv-kernel.o_binary ./nvidia.mod.o
-    ${NVIDIA_BINUITLS_DIR}/bin/ld -d -r -T ${base_dir}/module.lds -o nvidia-modeset.ko ./nv-modeset-linux.o ./nv-modeset-kernel.o_binary nvidia-modeset.mod.o
-    export LD_LIBRARY_PATH=${old_ld_path}
-    
-
-    # Copy the kernel modules to their final destination and generate the module dependencies
-    cp ${staging_dir}/*.ko ${NVIDIA_KMODS_DIR}/lib/modules/${KERNEL_VERSION}
-    cp ${archive_dir}/modules.order ${NVIDIA_KMODS_DIR}/lib/modules/${KERNEL_VERSION}
-    depmod -b ${NVIDIA_KMODS_DIR} ${KERNEL_VERSION}
+    IGNORE_CC_MISMATCH=1 nvidia-installer --kernel-module-only --no-drm --ui=none --no-nouveau-check -m=${KERNEL_TYPE} ${install_args[@]+"${install_args[@]}"}
 }
 
 # Execute binaries by root owning them first
@@ -347,6 +293,15 @@ _mount_rootfs() {
     _exec mount --make-private /sys
     mkdir -p ${RUN_DIR}/driver
     _exec mount --rbind / ${RUN_DIR}/driver
+
+    echo "Check SELinux status"
+    if [ -e /sys/fs/selinux ]; then
+        echo "SELinux is enabled"
+        echo "Change device files security context for selinux compatibility"
+        chcon -R -t container_file_t ${RUN_DIR}/driver/dev
+    else
+        echo "SELinux is disabled, skipping..."
+    fi
 }
 
 # Unmount the driver rootfs from the run directory.
